w4d5/RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :subs do
    resources :posts, only: [:new]
  end
  resources :posts, except: [:index, :destroy]
 end

w4d5/RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)
#  content    :text
#  author_id  :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  belongs_to :sub
  
end

w4d5/RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string(255)      not null
#  description :string(255)      not null
#  user_id     :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Sub < ActiveRecord::Base
  validates :title, :description, :user_id, presence: true
  validates :title, uniqueness: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  has_many :posts
end

w4d5/RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  
  validates :name, presence: true, uniqueness: true
  validates :email, :password_digest, :session_token, presence: true
  
  after_initialize :ensure_session_token
  has_many :subs
  has_many :posts, foreign_key: :author_id
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    
    #self.session_token
  end
  
  
  def self.find_by_credentials(name, password)
    @user = self.find_by(name: name)
    return nil if @user.nil?
    
    @user.is_password?(password) ? @user : nil
  end
  
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
end

w4d5/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user #class method?
    return nil unless self.session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
    # @user = User.find_by_session_token(session[:session_token])
    # return nil if @user.nil?
  end
  
  def login!
    @user.reset_session_token!
    self.session[:session_token] = @user.session_token
  end
  
  def self.logged_in?
    !current_user.nil? #current_user.present?
  end
  
  def logout!
    current_user.reset_session_token!
    self.session[:session_token] = nil
  end  
end

w4d5/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :must_be_post_author, only: [:edit, :update]
  
  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
    @subs = Sub.all
      # @sub = Sub.find(params[:sub][:id])
  end
  
  def create
    @post = Post.new(post_params)
    
    if @post.save
      redirect_to post_url(@post) 
    else
      flash.now[:errors] = @post.errors.full_messages
      @post = Post.new
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    @post.sub_id = params[:sub_id]
    @subs = Sub.all
    # @sub = Sub.find(params[:sub][:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @post = Post.find(params[:id])
      render :edit
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
  end
  
  def must_be_post_author
    @post = Post.find(params[:id])
    unless @post.author_id == current_user.id
      flash[:errors] = ["Can't edit someone else's post"]
      redirect_to sub_url(@post.sub)
    end
  end
end

w4d5/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:name], params[:user][:email])
    if @user.nil?
      flash.now[:errors] = ['Whatchu did, not okay']
      @user = User.new
      render :new
    else
      login!
      redirect_to user_url(@user)
    end
  end
  
  def destroy
    logout!
    redirect_to users_url
  end
  
  # private
  # def session_params
  #   params.require(:session).permit(:)
  # end
end

w4d5/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :must_be_moderator, only: [:edit, :update]
    
  def index
    @subs = Sub.all
    render :index
  end
  
  def new
    @sub = Sub.new
    render :new
  end
  
  def create
    @sub = Sub.new(sub_params)
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end
  
  def show
    @sub = Sub.find(params[:id])
    render :show
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description, :user_id)
  end
  
  def must_be_moderator
    unless Sub.find(params[:id]).moderator == current_user
      redirect_to subs_url
      flash[:errors] = ['Must be moderator']
    end
  end
end

w4d5/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login!
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def edit
    @user = User.find(params[:id])
    render :edit
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end 
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

w4d5/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d5/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

w4d5/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

w4d5/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

w4d5/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

w4d5/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless current_user.nil? %>
<p><%= link_to "Sign Out", session_url(), method: :delete %></p>
<% end %>

<% if flash[:errors] %>
<% flash[:errors].each do |error| %>
<p><%= error %></p>
<% end %>
<% end %>

<%= yield %>

</body>
</html>

w4d5/RedditClone/app/views/subs/_form.html.erb
<% method = (sub.persisted? ? "patch" : "post") %>
<% action = (sub.persisted? ? sub_url(sub) : subs_url) %>
<% submit = (sub.persisted? ? "Update sub" : "Create sub") %>

<form action="<%= action %>", method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
  
  <label for="sub_title">Sub title:</label>
  <input type="text"
         name="sub[title]"
         value="<%= sub.title %>"
         id="sub_title"> <br>
         
    <label for="description">Description:</label>
    <input type="text"
           name="sub[description]"
           value="<%= sub.description %>"
           id="description"> <br>
              

  <input type="hidden"
         name="sub[user_id]"
         value = "<%= current_user.id %>"> <br>
  
  
  <input type="submit" value="<%= submit %>">
  
  
</form>

w4d5/RedditClone/app/views/subs/edit.html.erb
<h1>Edit da Sub</h1>
<%= render "form", sub: @sub %>

w4d5/RedditClone/app/views/subs/index.html.erb
<h1> All the subs! </h1>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
    <li><%= link_to "Add post", new_post_url %></li>
</ul>

w4d5/RedditClone/app/views/subs/new.html.erb
<h1>Create un Sub</h1>
<%= render "form", sub: @sub %>

w4d5/RedditClone/app/views/subs/show.html.erb
<h1><%=   @sub.title %></h1>
<h2><%= @sub.description %> </h2>

<% @sub.posts.each do |post| %>
<p><%= link_to post.title, post_url(post) %></p>
<% end %>

<ul>
  <li><%= link_to "All the subs", subs_url %></li>
  <li><%= link_to "Moderator", user_url(@sub.moderator)%></li>
  <li><%= link_to "Add post", new_sub_post_url(@sub.id) %></li>
</ul>