w4d4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :index]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]
  resources :notes
end

w4d4/MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string(255)      not null
#  live       :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  validates :band_id, :name, presence: true
  validates :live, inclusion: { in: [true, false] }
  belongs_to :band
  has_many :tracks, dependent: :destroy

end

w4d4/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true
  
  has_many :albums, dependent: :destroy 
end

w4d4/MusicApp/app/models/note.rb
class Note < ActiveRecord::Base
  validates :text, :user_id, :track_id, presence: true
  
  belongs_to :user
  belongs_to :track
end

w4d4/MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  bonus      :boolean          default(FALSE)
#  lyrics     :text
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base
validates :album_id, :bonus, :lyrics, presence: true

belongs_to :album

has_many :notes
end

w4d4/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, uniqueness: true

  after_initialize { ensure_session_token }

  has_many :notes
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

end

w4d4/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_signin!
 def index
   @band = Band.find(params[:band_id])
   @albums = @band.albums
   render :index
 end

 def new
   @band = Band.find(params[:band_id])
   @album = Album.new(band_id: params[:band_id])
   render :new
 end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      @band = @album.band
      render :new
    end
  end
  
  def edit
    @band = Band.find(params[:band_id])
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to bands_url
  end

  def show
    @album = Album.find(params[:id])
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :live)
  end
end

w4d4/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user
  def current_user
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end
  
  def login_user!
    @user.reset_session_token!
    self.session[:session_token] = @user.session_token

    redirect_to users_url
  end

  def log_out!
    self.session[:session_token] = nil
  end

  def require_signin!
    redirect_to new_session_url if current_user.nil?
  end
end

w4d4/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  before_action :require_signin!

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      #@band = Band.new(band_params)
      render :new
    end
  end
  
  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id]).destroy
    redirect_to bands_url
  end

  def show
    @band = Band.find(params[:id])
  end

  
  private
  def band_params
    params.require(:band).permit(:name)
  end
end

w4d4/MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
  end

  def show

  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save

    redirect_to track_url(@note.track_id)
  end


  private
  def note_params
    params.require(:note).permit(:track_id, :user_id, :text)
  end
end

w4d4/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user.nil?
      @user = User.new
      render :new
    else 
      login_user!
    end
  end

  def destroy
    current_user.reset_session_token!
    self.session[:session_token] = nil

    redirect_to new_session_url
  end

end

w4d4/MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_signin!
  def index
    @album = Album.find(params[:album_id])
    @tracks = @album.tracks
    render :index
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      render :new
    end
  end

  # def edit
  #   @band = Band.find(params[:band_id])
  #   @album = Album.find(params[:id])
  #   render :edit
  # end

  # def update
  #   @album = Album.find(params[:id])

  #   if @album.update(album_params)
  #     redirect_to band_url(@band)
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   @album = Album.find(params[:id]).destroy
  #   redirect_to bands_url
  # end

  def show
    @track = Track.find(params[:id])
  end

  
  private
  def track_params
    params.require(:track).permit(:name, :lyrics, :bonus, :album_id)
  end
  
end

w4d4/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!
    else
      render :new
    end
  end

  def destroy

  end

  def show
    if self.current_user.nil?
      redirect_to new_session_url
    else
      @user = self.current_user
      render :show
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

w4d4/MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d4/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

w4d4/MusicApp/app/helpers/notes_helper.rb
module NotesHelper
end

w4d4/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

w4d4/MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

w4d4/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

w4d4/MusicApp/app/views/bands/_form.html.erb
<% action = (@band.persisted? ? band_url(@band) : bands_url) %>
<% method = (@band.persisted? ? :patch : :post) %>
<% submit = (@band.persisted? ? "Update band!" : "Create new band!") %>

<form action=<%= action %> method="POST">
  <input type="hidden" name="_method" value="<%= method %>">


   <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <label for="band_name">Band name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= @band.name %>">
  <br>

  <input type="submit" value=<%=submit%>>
</form>

w4d4/MusicApp/app/views/bands/edit.html.erb
<h1>Edit your band!</h1>
<%= render "form" %>

w4d4/MusicApp/app/views/bands/index.html.erb
<h1> All the bands!</h1>

<ul>
	<% @bands.each do |band| %>
		<li><%= link_to band.name, band_url(band.id) %></li>
	<% end %>
</ul>
<%= link_to "Create new band", new_band_url %>

w4d4/MusicApp/app/views/bands/new.html.erb
<h1> Create a new band! </h1> 
<%= render "form" %>

w4d4/MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1> 
<ul>
<li><%= link_to "All albums!", band_albums_url(@band) %> </li>
<li><%= link_to "Delete band!", band_url(@band), method: :delete %></li>
<li><%= link_to "All bands", bands_url %></li>
<li><%= link_to "Create an album", new_band_album_url(@band) %> </li>
</ul>

w4d4/MusicApp/app/views/notes/_form.html.erb
<h2>Make a new note!</h2>

<form action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <label for="note_text">Note</label>
  <br>

  <textarea id="note_text" name="note[text]"></textarea>
  <br>

  <input type="submit">
</form>

w4d4/MusicApp/app/views/notes/_note.html.erb
<pre><%= note.text %></pre>
<p>Authored by: <%= note.user.email %></p>

w4d4/MusicApp/app/views/tracks/_form.html.erb
<% action = (@track.persisted? ? track_url(@track) : tracks_url) %>
<% method = (@track.persisted? ? :patch : :post) %>
<% submit = (@track.persisted? ? "Update track!" : "Create new track!") %>


<form action=<%= action %> method=<%= method %>>

	 <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
	
	<label for="track_name">Track name</label>
	<input
		type="text"
		name="track[name]"
		id="track_name"
		value="<%= @track.name %>">
	<br>

<label>Album
<select name="track[album_id]">
	<% Album.all.each do |album| %>
	  <option value="<%= @album.id %>" 
	  	<%= "selected" if @album.name == album.name %>>
	  	<%= album.name.upcase %>
	  </option> 
   <% end %>
</select>
</label>
   <br>
   

	<label for="bonus">Bonus Track</label> 
	<input type="radio"
		   name="track[bonus]"
		   value="t">

	<label for="bonus">Regular Track</label> 
	<input type="radio"
		   name="track[bonus]"
		   checked
		   value="f">
   <br>

   <label for="lyrics">Lyrics</label>
	<input
		type="text"
		name="track[lyrics]"
		id="lyrics"
		value="<%= @track.lyrics %>">
	<br>

    <input type="submit" value=<%= submit %>>
</form>

w4d4/MusicApp/app/views/tracks/new.html.erb
<h1> Make a new track! </h1> 
<%= render "form" %>

w4d4/MusicApp/app/views/tracks/show.html.erb
<h1> <%=@track.name %> </h1> 
<ul>
<li> <%= @track.album.name %> </li> 
<li> <%= link_to @track.album.band.name, album_url(@track.album) %> </li> 
<li> <%= @track.bonus? ? "Bonus track" : "Regular track" %> </li>
</ul> 

<%= "Lyrics: #{@track.lyrics}" %>
<% @track.notes.each do |note| %>
	<%= render "notes/note", note: note %>
<% end %>

<%= render "notes/form", track: @track %>

w4d4/MusicApp/app/views/users/index.html.erb
<h1> All the users!</h1>

<ul>
<% @users.each do |user| %>
	<li><%= user.email %></li>
<% end %>
</ul>

w4d4/MusicApp/app/views/users/new.html.erb
<h1> Sign up here!</h1>
<form action="/users" method="POST">

   <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <label for="user_email">Email</label>
  <input
    type="text"
    name="user[email]"
    id="user_email"
    value="<%= @user.email %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="Sign Up">
</form>

w4d4/MusicApp/app/views/users/show.html.erb
<h1> <%= @user.email %> </h1> 