w4d2-d3/ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:index, :new, :create]
  resource :session, only: [:new, :destroy, :create]
end

w4d2-d3/ninety-nine-cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string(255)      not null
#  name        :string(255)      not null
#  sex         :string(255)      not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Cat < ActiveRecord::Base
  COLORS = ["white", "calico", "magenta", "black"]
  belongs_to(
    :owner,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
  SEX = ["m","f"]
  
  
  validates :birth_date, :sex, :name, :color,  presence: true
  validates :birth_date, :timeliness => {:on_or_before => lambda { Date.current }, :type => :date}
  validates :color, inclusion: COLORS
  validates :sex, inclusion: SEX
  
  def age
    Date.current.year - birth_date.year
  end
  
  has_many(:cat_rental_requests, dependent: :destroy)
end

w4d2-d3/ninety-nine-cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string(255)      default("PENDING"), not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  STATUS = ["PENDING", "APPROVED", "DENIED"]
  
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: STATUS
  validate :overlapping_approved_requests
  # after_initialize do
  #   puts "SETTING STATUS *******************************"
  #   self.status ||= "PENDING"
  # end
  
  belongs_to(:cat)
    
  def approve!
    self.status = "APPROVED"
    self.save!
    overlapping_requests.each { |request| request.deny! }
  end

  def deny!
    self.status = 'DENIED'
  end
  
  def overlapping_requests
    all_requests = CatRentalRequest.all
    
    all_requests.select do |request|#self.?
      start_date.between?(request.start_date, request.end_date) ||
        end_date.between?(request.start_date, request.end_date)
    end
  end
  
  def overlapping_approved_requests
    any_requests = overlapping_requests.any? do |request|
      request.status == "APPROVED"
      end  
      if any_requests
        errors[:cat_id] << "Date taken, choose another cat!"
      end
  end
end

w4d2-d3/ninety-nine-cats/app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, :session_token, uniqueness: true
  
  has_many :cats
  
  after_initialize do 
    ensure_session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save! #update?
    self.session_token
  end
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    
    
     user.is_password?(password) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

w4d2-d3/ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
   return nil if self.session[:session_token].nil?
   @user ||= User.find_by(session_token: self.session[:session_token])
  end
 helper_method :current_user

 def login_user!
   @user.reset_session_token!
   self.session[:session_token] = @user.session_token
   redirect_to cats_url
 end


end

w4d2-d3/ninety-nine-cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @crr = CatRentalRequest.all
    render :index
  end
  
  def new
    @crr = CatRentalRequest.new
    render :new
  end
  
  def create
    @crr = CatRentalRequest.new(crr_params)
    @crr.user_id = current_user.id
    @cat = Cat.find(@crr.cat_id)
    if @crr.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end
  
  def approve
    @crr = CatRentalRequest.find(params[:id])
    @crr.approve!
  end
  
  def deny
    @crr = CatRentalRequest.find(params[:id])
    @crr.deny!
  end
  
  
  private
    def crr_params
      params[:crr].
        permit(:cat_id, :status, :start_date, :end_date, :id)
    end
  
  
end

w4d2-d3/ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action except: [:index] do
    unless current_user
      redirect_to new_session_url
    end
  end
  
    
  before_action only: [:edit, :update] do
    @cat = Cat.find(params[:id])

    unless @cat.user_id == current_user.id
      redirect_to cats_url
    end
  end
  

  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
      # render json: @cat.errors.full_messages, status: :unproccesable_entity
    end
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  
  
  private
  def cat_params
    params[:cat].permit(:name, :color, :sex, :description, :birth_date, :id, :user_id)
  end
end

w4d2-d3/ninety-nine-cats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action only: [:new, :create] do 
    if current_user
      redirect_to cats_url
    end
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
    if @user.nil?
      render :new
    else
      login_user!
    end
  end
  
  def destroy
    current_user.reset_session_token!
    self.session[:session_token] = nil
    
    redirect_to new_session_url #sessions?
  end
  
end
#
# <input typ="text" name="user[user_name]">
#
#
# params: {user: {user_name: "shawna"}}

w4d2-d3/ninety-nine-cats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action only: [:create, :new] do 
    if current_user
      redirect_to cats_url
    end
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login_user!
    else
      render :new
    end
    
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

w4d2-d3/ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d2-d3/ninety-nine-cats/app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

w4d2-d3/ninety-nine-cats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d2-d3/ninety-nine-cats/app/helpers/sessions_helper.rb
module SessionsHelper
end

w4d2-d3/ninety-nine-cats/app/helpers/users_helper.rb
module UsersHelper
end

w4d2-d3/ninety-nine-cats/app/views/cat_rental_requests/index.html.erb
<h1>All the cats</h1>

  <ul>
    <%@crr.each do |crr|%>
      <li><%=link_to crr.cat.name, cat_url(crr.cat_id)%></li>
    <% end %>  
    
  

</ul>

w4d2-d3/ninety-nine-cats/app/views/cat_rental_requests/new.html.erb
<h1>Make a new cat rental request!</h1>

<form action = "<%=cat_rental_requests_url%>" method = "POST">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
    <select name="crr[cat_id]">
      <option value="other">Choose Cat</label>
        <% Cat.all.each do |rental_cat| %>
          <option value="<%= rental_cat.id %>"
                  <%= "selected" if rental_cat.id == @crr.id %>>
            <%= rental_cat.name %>
          </option>
        <% end %>
    </select>
    
    <label for="start_date">Start Date</label>
    <input type="date"
           name="crr[start_date]"
           id="start_date"
           value="<%=@crr.start_date%>">
           
   <label for="end_date">End Date</label>
   <input type="date"
          name="crr[end_date]"
          id="end_date"
          value="<%=@crr.end_date%>">
          
    <input type="submit" value="Order a Cat!">
    
  </form>

w4d2-d3/ninety-nine-cats/app/views/cats/_form.html.erb
    
    <% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!" %>
    
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    
    <label for="cat_name">Name</label>
    <input type="text"
           name="cat[name]"
           id="cat_name"
           value="<%= cat.name %>">
           
    <label for="birth_date">Birth Date</label>
    <input type="date"
           name="cat[birth_date]"
           id="birth_date"
           value="<%=cat.birth_date%>">
           
  
    <select name="cat[color]">
      <option value="other">Choose Color</label>
        <% Cat::COLORS.each do |color| %>
          <option value="<%= color %>"
                  <%= "selected" if cat.color == color %>>
            <%= color.capitalize %>
          </option>
        <% end %>
    </select>

    <% Cat::SEX.each do |sex| %>
      <label for="sex"><%= sex %></label>
      <input type="radio"
             name="cat[sex]"
             value="<%= sex %>"
             <%= "checked" if cat.sex == sex %>>
    <% end %>
    <br>
    <br>
    
    <label for="Description">Description</label>
    <br>
      <textarea ID="Description" rows="4" cols="50"
               name="cat[description]"><%=cat.description%></textarea>
              
    <input type="submit" value=<%= submit_text %>>

w4d2-d3/ninety-nine-cats/app/views/cats/edit.html.erb
<h1> Edit a Cat!</h1>

<form action="<%= cat_url(@cat) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <%= render "form", cat: @cat %>
</form>

w4d2-d3/ninety-nine-cats/app/views/cats/index.html.erb
<h1>All the cats</h1>

  <ul>
    <%@cats.each do |cat|%>
      <li><%=link_to cat.name, cat_url(cat.id)%></li>
    <% end %>  
    
  

</ul>

w4d2-d3/ninety-nine-cats/app/views/cats/new.html.erb
<h1> Build a Cat!</h1>

<form action="<%= cats_url %>" method="POST">

  <%= render "form", cat: @cat %>
</form>

w4d2-d3/ninety-nine-cats/app/views/cats/show.html.erb
<h1><%=@cat.name%></h1>

<head>
  <style>
  table, th, td {
      border: 5px solid black; border-spacing: 2px;
  }
  </style>
  
  </head>

<table>
  <tr>
    <th>Age</th>
    <th>Color</th> 
    <th>Sex</th>
  </tr>
  <tr>
    <td><%=@cat.age%></td> 
    <td><%=@cat.color%></td>
    <td><%=@cat.sex%></td>
  </tr>
</table>
<br>
<ol>
<%@cat.cat_rental_requests.each do |request|%>
<li><%="From #{request.start_date} to #{request.end_date}"%></li>
    <%= button_to "Approve", approve_cat_rental_request_url%>
     <%= button_to "Deny", deny_cat_rental_request_url%>
<%end%>
<br>
</ol>




<%=@cat.description%>

<%= link_to "All the cats", cats_url %>